// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: default_blocked_words.sql

package sqlcgen

import (
	"context"
)

const addDefaultBlockedWord = `-- name: AddDefaultBlockedWord :one
INSERT INTO default_blocked_words (term) VALUES ($1) RETURNING id, term
`

func (q *Queries) AddDefaultBlockedWord(ctx context.Context, term string) (DefaultBlockedWord, error) {
	row := q.db.QueryRow(ctx, addDefaultBlockedWord, term)
	var i DefaultBlockedWord
	err := row.Scan(&i.ID, &i.Term)
	return i, err
}

const listDefaultBlockedWords = `-- name: ListDefaultBlockedWords :many
SELECT id, term FROM default_blocked_words ORDER BY term
`

func (q *Queries) ListDefaultBlockedWords(ctx context.Context) ([]DefaultBlockedWord, error) {
	rows, err := q.db.Query(ctx, listDefaultBlockedWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DefaultBlockedWord
	for rows.Next() {
		var i DefaultBlockedWord
		if err := rows.Scan(&i.ID, &i.Term); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceDefaultBlockedWords = `-- name: ReplaceDefaultBlockedWords :exec
DELETE FROM default_blocked_words
`

// Substitui a lista global inteira (usada pela tela admin de Configurações
// Globais, que edita a lista como um todo, não item a item).
func (q *Queries) ReplaceDefaultBlockedWords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, replaceDefaultBlockedWords)
	return err
}
