// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketplace_scan_settings.sql

package sqlcgen

import (
	"context"
)

const deleteMarketplaceScanSettingsNotIn = `-- name: DeleteMarketplaceScanSettingsNotIn :exec
DELETE FROM marketplace_scan_settings
WHERE marketplace_slug != ALL($1::text[])
`

// Remove configurações de marketplaces que não vieram na última
// atualização (voltam a usar o fallback global) — mesmo padrão de replace
// completo usado em ReplaceDefaultBlockedWords.
func (q *Queries) DeleteMarketplaceScanSettingsNotIn(ctx context.Context, marketplaceSlugs []string) error {
	_, err := q.db.Exec(ctx, deleteMarketplaceScanSettingsNotIn, marketplaceSlugs)
	return err
}

const listMarketplaceScanSettings = `-- name: ListMarketplaceScanSettings :many
SELECT marketplace_slug, min_interval_minutes, max_interval_minutes FROM marketplace_scan_settings ORDER BY marketplace_slug
`

func (q *Queries) ListMarketplaceScanSettings(ctx context.Context) ([]MarketplaceScanSetting, error) {
	rows, err := q.db.Query(ctx, listMarketplaceScanSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketplaceScanSetting
	for rows.Next() {
		var i MarketplaceScanSetting
		if err := rows.Scan(&i.MarketplaceSlug, &i.MinIntervalMinutes, &i.MaxIntervalMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMarketplaceScanSetting = `-- name: UpsertMarketplaceScanSetting :one
INSERT INTO marketplace_scan_settings (marketplace_slug, min_interval_minutes, max_interval_minutes)
VALUES ($1, $2, $3)
ON CONFLICT (marketplace_slug) DO UPDATE SET
    min_interval_minutes = EXCLUDED.min_interval_minutes,
    max_interval_minutes = EXCLUDED.max_interval_minutes
RETURNING marketplace_slug, min_interval_minutes, max_interval_minutes
`

type UpsertMarketplaceScanSettingParams struct {
	MarketplaceSlug    string `json:"marketplace_slug"`
	MinIntervalMinutes int32  `json:"min_interval_minutes"`
	MaxIntervalMinutes int32  `json:"max_interval_minutes"`
}

func (q *Queries) UpsertMarketplaceScanSetting(ctx context.Context, arg UpsertMarketplaceScanSettingParams) (MarketplaceScanSetting, error) {
	row := q.db.QueryRow(ctx, upsertMarketplaceScanSetting, arg.MarketplaceSlug, arg.MinIntervalMinutes, arg.MaxIntervalMinutes)
	var i MarketplaceScanSetting
	err := row.Scan(&i.MarketplaceSlug, &i.MinIntervalMinutes, &i.MaxIntervalMinutes)
	return i, err
}
