// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChannelType string

const (
	ChannelTypeWhatsapp ChannelType = "whatsapp"
	ChannelTypeTelegram ChannelType = "telegram"
	ChannelTypeEmail    ChannelType = "email"
	ChannelTypeInApp    ChannelType = "in_app"
)

func (e *ChannelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelType(s)
	case string:
		*e = ChannelType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelType: %T", src)
	}
	return nil
}

type NullChannelType struct {
	ChannelType ChannelType `json:"channel_type"`
	Valid       bool        `json:"valid"` // Valid is true if ChannelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelType) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelType), nil
}

type NotificationStatus string

const (
	NotificationStatusPending NotificationStatus = "pending"
	NotificationStatusSent    NotificationStatus = "sent"
	NotificationStatusFailed  NotificationStatus = "failed"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type NotificationTrigger string

const (
	NotificationTriggerNewOffer  NotificationTrigger = "new_offer"
	NotificationTriggerPriceDrop NotificationTrigger = "price_drop"
)

func (e *NotificationTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTrigger(s)
	case string:
		*e = NotificationTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTrigger: %T", src)
	}
	return nil
}

type NullNotificationTrigger struct {
	NotificationTrigger NotificationTrigger `json:"notification_trigger"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTrigger), nil
}

type ScanStatus string

const (
	ScanStatusSuccess ScanStatus = "success"
	ScanStatusPartial ScanStatus = "partial"
	ScanStatusFailed  ScanStatus = "failed"
)

func (e *ScanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatus(s)
	case string:
		*e = ScanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatus: %T", src)
	}
	return nil
}

type NullScanStatus struct {
	ScanStatus ScanStatus `json:"scan_status"`
	Valid      bool       `json:"valid"` // Valid is true if ScanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatus), nil
}

type DefaultBlockedWord struct {
	ID   pgtype.UUID `json:"id"`
	Term string      `json:"term"`
}

type Marketplace struct {
	Slug string `json:"slug"`
}

type Notification struct {
	ID          pgtype.UUID         `json:"id"`
	UserID      pgtype.UUID         `json:"user_id"`
	OfferID     pgtype.UUID         `json:"offer_id"`
	ChannelType ChannelType         `json:"channel_type"`
	Trigger     NotificationTrigger `json:"trigger"`
	Status      NotificationStatus  `json:"status"`
	Attempts    int32               `json:"attempts"`
	LastError   *string             `json:"last_error"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	SentAt      pgtype.Timestamptz  `json:"sent_at"`
	ReadAt      pgtype.Timestamptz  `json:"read_at"`
}

type Offer struct {
	ID                pgtype.UUID        `json:"id"`
	WatchID           pgtype.UUID        `json:"watch_id"`
	MarketplaceSlug   string             `json:"marketplace_slug"`
	ExternalID        string             `json:"external_id"`
	Url               string             `json:"url"`
	Title             string             `json:"title"`
	ImageUrl          string             `json:"image_url"`
	PriceCents        int64              `json:"price_cents"`
	Classification    pgtype.Numeric     `json:"classification"`
	Available         bool               `json:"available"`
	FirstSeenScanID   pgtype.UUID        `json:"first_seen_scan_id"`
	LastCheckedScanID pgtype.UUID        `json:"last_checked_scan_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Monitored         bool               `json:"monitored"`
}

type OfferPricePoint struct {
	ID         pgtype.UUID        `json:"id"`
	OfferID    pgtype.UUID        `json:"offer_id"`
	PriceCents int64              `json:"price_cents"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	ScanID     pgtype.UUID        `json:"scan_id"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	Name string `json:"name"`
}

type Scan struct {
	ID              pgtype.UUID        `json:"id"`
	WatchID         pgtype.UUID        `json:"watch_id"`
	Status          ScanStatus         `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	OffersFound     int32              `json:"offers_found"`
	NewOffersCount  int32              `json:"new_offers_count"`
	SeenOffersCount int32              `json:"seen_offers_count"`
}

type ScanMarketplaceFailure struct {
	ScanID          pgtype.UUID `json:"scan_id"`
	MarketplaceSlug string      `json:"marketplace_slug"`
	ErrorMessage    *string     `json:"error_message"`
}

type ScanSetting struct {
	ID                 bool               `json:"id"`
	MinIntervalMinutes int32              `json:"min_interval_minutes"`
	MaxIntervalMinutes int32              `json:"max_interval_minutes"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DefaultCity        string             `json:"default_city"`
	DefaultState       string             `json:"default_state"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     *string            `json:"username"`
}

type UserChannel struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	ChannelType       ChannelType        `json:"channel_type"`
	Destination       string             `json:"destination"`
	TelegramLinkToken *string            `json:"telegram_link_token"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Watch struct {
	ID                        pgtype.UUID        `json:"id"`
	UserID                    pgtype.UUID        `json:"user_id"`
	Name                      string             `json:"name"`
	TargetPriceCents          int64              `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric     `json:"tolerance_percent"`
	MaxOffers                 int32              `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric     `json:"price_drop_threshold_percent"`
	Active                    bool               `json:"active"`
	NextScanAt                pgtype.Timestamptz `json:"next_scan_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	City                      *string            `json:"city"`
	State                     *string            `json:"state"`
}

type WatchBlockedWord struct {
	ID      pgtype.UUID `json:"id"`
	WatchID pgtype.UUID `json:"watch_id"`
	Term    string      `json:"term"`
}

type WatchKeyword struct {
	ID      pgtype.UUID `json:"id"`
	WatchID pgtype.UUID `json:"watch_id"`
	Term    string      `json:"term"`
}

type WatchMarketplace struct {
	WatchID         pgtype.UUID `json:"watch_id"`
	MarketplaceSlug string      `json:"marketplace_slug"`
}
