// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceDropNotification = `-- name: CreatePriceDropNotification :one
INSERT INTO notifications (user_id, offer_id, channel_type, trigger, status, sent_at)
VALUES ($1, $2, 'in_app', 'price_drop', 'sent', now())
RETURNING id, user_id, offer_id, channel_type, trigger, status, attempts, last_error, created_at, sent_at, read_at
`

type CreatePriceDropNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	OfferID pgtype.UUID `json:"offer_id"`
}

// Notificação in-app de queda de preço de uma Offer monitorada. channel_type
// fica fixo em 'in_app' e status em 'sent' — ainda não existe disparo real
// por canal externo (ver ADR 0001), só o registro in-app; os demais campos
// existem no schema para quando isso for implementado.
func (q *Queries) CreatePriceDropNotification(ctx context.Context, arg CreatePriceDropNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createPriceDropNotification, arg.UserID, arg.OfferID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OfferID,
		&i.ChannelType,
		&i.Trigger,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT n.id, n.user_id, n.offer_id, n.channel_type, n.trigger, n.status, n.attempts, n.last_error, n.created_at, n.sent_at, n.read_at, o.title AS offer_title, o.price_cents AS offer_price_cents,
    o.url AS offer_url, w.id AS watch_id, w.name AS watch_name
FROM notifications n
JOIN offers o ON o.id = n.offer_id
JOIN watches w ON w.id = o.watch_id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2
`

type ListNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListNotificationsByUserRow struct {
	ID              pgtype.UUID         `json:"id"`
	UserID          pgtype.UUID         `json:"user_id"`
	OfferID         pgtype.UUID         `json:"offer_id"`
	ChannelType     ChannelType         `json:"channel_type"`
	Trigger         NotificationTrigger `json:"trigger"`
	Status          NotificationStatus  `json:"status"`
	Attempts        int32               `json:"attempts"`
	LastError       *string             `json:"last_error"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
	SentAt          pgtype.Timestamptz  `json:"sent_at"`
	ReadAt          pgtype.Timestamptz  `json:"read_at"`
	OfferTitle      string              `json:"offer_title"`
	OfferPriceCents int64               `json:"offer_price_cents"`
	OfferUrl        string              `json:"offer_url"`
	WatchID         pgtype.UUID         `json:"watch_id"`
	WatchName       string              `json:"watch_name"`
}

// Junta com offers/watches pra dar contexto exibível (título, preço, nome
// do Watch) sem a UI precisar de uma segunda chamada por notificação.
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]ListNotificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsByUserRow
	for rows.Next() {
		var i ListNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OfferID,
			&i.ChannelType,
			&i.Trigger,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
			&i.ReadAt,
			&i.OfferTitle,
			&i.OfferPriceCents,
			&i.OfferUrl,
			&i.WatchID,
			&i.WatchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 RETURNING id, user_id, offer_id, channel_type, trigger, status, attempts, last_error, created_at, sent_at, read_at
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OfferID,
		&i.ChannelType,
		&i.Trigger,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}
