// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, watch_id, marketplace_slug, external_id, url, title, image_url, price_cents, classification, available, first_seen_scan_id, last_checked_scan_id, created_at, updated_at, monitored FROM offers WHERE id = $1
`

func (q *Queries) GetOfferByID(ctx context.Context, id pgtype.UUID) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferByID, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.MarketplaceSlug,
		&i.ExternalID,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.PriceCents,
		&i.Classification,
		&i.Available,
		&i.FirstSeenScanID,
		&i.LastCheckedScanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Monitored,
	)
	return i, err
}

const insertOfferPricePointIfChanged = `-- name: InsertOfferPricePointIfChanged :exec
INSERT INTO offer_price_points (offer_id, price_cents, scan_id)
SELECT $1, $2, $3
WHERE NOT EXISTS (
    SELECT 1 FROM offer_price_points
    WHERE offer_id = $1
    ORDER BY observed_at DESC
    LIMIT 1
) OR (
    SELECT price_cents FROM offer_price_points
    WHERE offer_id = $1
    ORDER BY observed_at DESC
    LIMIT 1
) != $2
`

type InsertOfferPricePointIfChangedParams struct {
	OfferID    pgtype.UUID `json:"offer_id"`
	PriceCents int64       `json:"price_cents"`
	ScanID     pgtype.UUID `json:"scan_id"`
}

// Um novo ponto de Histórico de Preço só é registrado quando o valor difere
// do último observado (reverificação sem mudança não gera ponto novo).
func (q *Queries) InsertOfferPricePointIfChanged(ctx context.Context, arg InsertOfferPricePointIfChangedParams) error {
	_, err := q.db.Exec(ctx, insertOfferPricePointIfChanged, arg.OfferID, arg.PriceCents, arg.ScanID)
	return err
}

const listOfferPricePoints = `-- name: ListOfferPricePoints :many
SELECT id, offer_id, price_cents, observed_at, scan_id FROM offer_price_points WHERE offer_id = $1 ORDER BY observed_at ASC
`

func (q *Queries) ListOfferPricePoints(ctx context.Context, offerID pgtype.UUID) ([]OfferPricePoint, error) {
	rows, err := q.db.Query(ctx, listOfferPricePoints, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferPricePoint
	for rows.Next() {
		var i OfferPricePoint
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.PriceCents,
			&i.ObservedAt,
			&i.ScanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOffersUnavailableNotIn = `-- name: MarkOffersUnavailableNotIn :exec
UPDATE offers SET available = FALSE, updated_at = now()
WHERE watch_id = $1
  AND available
  AND external_id != ALL($2::text[])
`

type MarkOffersUnavailableNotInParams struct {
	WatchID         pgtype.UUID `json:"watch_id"`
	SeenExternalIds []string    `json:"seen_external_ids"`
}

// Marca como indisponíveis as Offers que estavam no top-N e não vieram mais
// no resultado do Scan atual (anúncio vendido/removido).
func (q *Queries) MarkOffersUnavailableNotIn(ctx context.Context, arg MarkOffersUnavailableNotInParams) error {
	_, err := q.db.Exec(ctx, markOffersUnavailableNotIn, arg.WatchID, arg.SeenExternalIds)
	return err
}

const setOfferMonitored = `-- name: SetOfferMonitored :one
UPDATE offers SET monitored = $2, updated_at = now() WHERE id = $1 RETURNING id, watch_id, marketplace_slug, external_id, url, title, image_url, price_cents, classification, available, first_seen_scan_id, last_checked_scan_id, created_at, updated_at, monitored
`

type SetOfferMonitoredParams struct {
	ID        pgtype.UUID `json:"id"`
	Monitored bool        `json:"monitored"`
}

func (q *Queries) SetOfferMonitored(ctx context.Context, arg SetOfferMonitoredParams) (Offer, error) {
	row := q.db.QueryRow(ctx, setOfferMonitored, arg.ID, arg.Monitored)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.MarketplaceSlug,
		&i.ExternalID,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.PriceCents,
		&i.Classification,
		&i.Available,
		&i.FirstSeenScanID,
		&i.LastCheckedScanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Monitored,
	)
	return i, err
}

const topOffersByWatch = `-- name: TopOffersByWatch :many
SELECT o.id, o.watch_id, o.marketplace_slug, o.external_id, o.url, o.title, o.image_url, o.price_cents, o.classification, o.available, o.first_seen_scan_id, o.last_checked_scan_id, o.created_at, o.updated_at, o.monitored FROM offers o
WHERE o.watch_id = $1 AND o.available
  AND (o.monitored OR o.id IN (
    SELECT o2.id FROM offers o2
    WHERE o2.watch_id = $1 AND o2.available
    ORDER BY o2.classification DESC
    LIMIT $2
  ))
ORDER BY o.monitored DESC, o.classification DESC
`

type TopOffersByWatchParams struct {
	WatchID pgtype.UUID `json:"watch_id"`
	Limit   int32       `json:"limit"`
}

// Offers atualmente exibidas: as top-N por Classificação (as únicas
// reverificadas a cada Scan, conforme o domínio) mais as marcadas como
// monitored, que sempre aparecem independente do corte do limite.
func (q *Queries) TopOffersByWatch(ctx context.Context, arg TopOffersByWatchParams) ([]Offer, error) {
	rows, err := q.db.Query(ctx, topOffersByWatch, arg.WatchID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.WatchID,
			&i.MarketplaceSlug,
			&i.ExternalID,
			&i.Url,
			&i.Title,
			&i.ImageUrl,
			&i.PriceCents,
			&i.Classification,
			&i.Available,
			&i.FirstSeenScanID,
			&i.LastCheckedScanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Monitored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOffer = `-- name: UpsertOffer :one
INSERT INTO offers (
    watch_id, marketplace_slug, external_id, url, title, image_url,
    price_cents, classification, available, first_seen_scan_id, last_checked_scan_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, TRUE, $9, $9)
ON CONFLICT (watch_id, marketplace_slug, external_id) DO UPDATE SET
    url = EXCLUDED.url,
    title = EXCLUDED.title,
    image_url = EXCLUDED.image_url,
    price_cents = EXCLUDED.price_cents,
    classification = EXCLUDED.classification,
    available = TRUE,
    last_checked_scan_id = EXCLUDED.last_checked_scan_id,
    updated_at = now()
RETURNING id, watch_id, marketplace_slug, external_id, url, title, image_url, price_cents, classification, available, first_seen_scan_id, last_checked_scan_id, created_at, updated_at, monitored, (xmax = 0) AS is_new
`

type UpsertOfferParams struct {
	WatchID         pgtype.UUID    `json:"watch_id"`
	MarketplaceSlug string         `json:"marketplace_slug"`
	ExternalID      string         `json:"external_id"`
	Url             string         `json:"url"`
	Title           string         `json:"title"`
	ImageUrl        string         `json:"image_url"`
	PriceCents      int64          `json:"price_cents"`
	Classification  pgtype.Numeric `json:"classification"`
	FirstSeenScanID pgtype.UUID    `json:"first_seen_scan_id"`
}

type UpsertOfferRow struct {
	ID                pgtype.UUID        `json:"id"`
	WatchID           pgtype.UUID        `json:"watch_id"`
	MarketplaceSlug   string             `json:"marketplace_slug"`
	ExternalID        string             `json:"external_id"`
	Url               string             `json:"url"`
	Title             string             `json:"title"`
	ImageUrl          string             `json:"image_url"`
	PriceCents        int64              `json:"price_cents"`
	Classification    pgtype.Numeric     `json:"classification"`
	Available         bool               `json:"available"`
	FirstSeenScanID   pgtype.UUID        `json:"first_seen_scan_id"`
	LastCheckedScanID pgtype.UUID        `json:"last_checked_scan_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Monitored         bool               `json:"monitored"`
	IsNew             bool               `json:"is_new"`
}

// Cria a Offer se for a primeira vez que este anúncio aparece neste Watch,
// ou atualiza os dados observados se já existia (reverificação). first_seen_scan_id
// só é setado na criação; last_checked_scan_id é sempre atualizado.
func (q *Queries) UpsertOffer(ctx context.Context, arg UpsertOfferParams) (UpsertOfferRow, error) {
	row := q.db.QueryRow(ctx, upsertOffer,
		arg.WatchID,
		arg.MarketplaceSlug,
		arg.ExternalID,
		arg.Url,
		arg.Title,
		arg.ImageUrl,
		arg.PriceCents,
		arg.Classification,
		arg.FirstSeenScanID,
	)
	var i UpsertOfferRow
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.MarketplaceSlug,
		&i.ExternalID,
		&i.Url,
		&i.Title,
		&i.ImageUrl,
		&i.PriceCents,
		&i.Classification,
		&i.Available,
		&i.FirstSeenScanID,
		&i.LastCheckedScanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Monitored,
		&i.IsNew,
	)
	return i, err
}
