// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScan = `-- name: CreateScan :one
INSERT INTO scans (watch_id, status) VALUES ($1, 'success') RETURNING id, watch_id, status, started_at, finished_at, offers_found
`

func (q *Queries) CreateScan(ctx context.Context, watchID pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan, watchID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OffersFound,
	)
	return i, err
}

const finishScan = `-- name: FinishScan :one
UPDATE scans SET status = $2, finished_at = now(), offers_found = $3
WHERE id = $1
RETURNING id, watch_id, status, started_at, finished_at, offers_found
`

type FinishScanParams struct {
	ID          pgtype.UUID `json:"id"`
	Status      ScanStatus  `json:"status"`
	OffersFound int32       `json:"offers_found"`
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, finishScan, arg.ID, arg.Status, arg.OffersFound)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OffersFound,
	)
	return i, err
}

const listScanMarketplaceFailures = `-- name: ListScanMarketplaceFailures :many
SELECT scan_id, marketplace_slug, error_message FROM scan_marketplace_failures WHERE scan_id = $1
`

func (q *Queries) ListScanMarketplaceFailures(ctx context.Context, scanID pgtype.UUID) ([]ScanMarketplaceFailure, error) {
	rows, err := q.db.Query(ctx, listScanMarketplaceFailures, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanMarketplaceFailure
	for rows.Next() {
		var i ScanMarketplaceFailure
		if err := rows.Scan(&i.ScanID, &i.MarketplaceSlug, &i.ErrorMessage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansByWatch = `-- name: ListScansByWatch :many
SELECT id, watch_id, status, started_at, finished_at, offers_found FROM scans WHERE watch_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListScansByWatchParams struct {
	WatchID pgtype.UUID `json:"watch_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListScansByWatch(ctx context.Context, arg ListScansByWatchParams) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listScansByWatch, arg.WatchID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.WatchID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OffersFound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScanMarketplaceFailure = `-- name: RecordScanMarketplaceFailure :exec
INSERT INTO scan_marketplace_failures (scan_id, marketplace_slug, error_message)
VALUES ($1, $2, $3)
`

type RecordScanMarketplaceFailureParams struct {
	ScanID          pgtype.UUID `json:"scan_id"`
	MarketplaceSlug string      `json:"marketplace_slug"`
	ErrorMessage    *string     `json:"error_message"`
}

func (q *Queries) RecordScanMarketplaceFailure(ctx context.Context, arg RecordScanMarketplaceFailureParams) error {
	_, err := q.db.Exec(ctx, recordScanMarketplaceFailure, arg.ScanID, arg.MarketplaceSlug, arg.ErrorMessage)
	return err
}
