// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_settings.sql

package sqlcgen

import (
	"context"
)

const getScanSettings = `-- name: GetScanSettings :one
SELECT id, updated_at, default_city, default_state FROM scan_settings WHERE id = TRUE
`

func (q *Queries) GetScanSettings(ctx context.Context) (ScanSetting, error) {
	row := q.db.QueryRow(ctx, getScanSettings)
	var i ScanSetting
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.DefaultCity,
		&i.DefaultState,
	)
	return i, err
}

const updateScanSettings = `-- name: UpdateScanSettings :one
UPDATE scan_settings
SET default_city = $1,
    default_state = $2,
    updated_at = now()
WHERE id = TRUE
RETURNING id, updated_at, default_city, default_state
`

type UpdateScanSettingsParams struct {
	DefaultCity  string `json:"default_city"`
	DefaultState string `json:"default_state"`
}

func (q *Queries) UpdateScanSettings(ctx context.Context, arg UpdateScanSettingsParams) (ScanSetting, error) {
	row := q.db.QueryRow(ctx, updateScanSettings, arg.DefaultCity, arg.DefaultState)
	var i ScanSetting
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.DefaultCity,
		&i.DefaultState,
	)
	return i, err
}
