// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_settings.sql

package sqlcgen

import (
	"context"
)

const getScanSettings = `-- name: GetScanSettings :one
SELECT id, min_interval_minutes, max_interval_minutes, updated_at FROM scan_settings WHERE id = TRUE
`

func (q *Queries) GetScanSettings(ctx context.Context) (ScanSetting, error) {
	row := q.db.QueryRow(ctx, getScanSettings)
	var i ScanSetting
	err := row.Scan(
		&i.ID,
		&i.MinIntervalMinutes,
		&i.MaxIntervalMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScanSettings = `-- name: UpdateScanSettings :one
UPDATE scan_settings
SET min_interval_minutes = $1, max_interval_minutes = $2, updated_at = now()
WHERE id = TRUE
RETURNING id, min_interval_minutes, max_interval_minutes, updated_at
`

type UpdateScanSettingsParams struct {
	MinIntervalMinutes int32 `json:"min_interval_minutes"`
	MaxIntervalMinutes int32 `json:"max_interval_minutes"`
}

func (q *Queries) UpdateScanSettings(ctx context.Context, arg UpdateScanSettingsParams) (ScanSetting, error) {
	row := q.db.QueryRow(ctx, updateScanSettings, arg.MinIntervalMinutes, arg.MaxIntervalMinutes)
	var i ScanSetting
	err := row.Scan(
		&i.ID,
		&i.MinIntervalMinutes,
		&i.MaxIntervalMinutes,
		&i.UpdatedAt,
	)
	return i, err
}
