// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role, username)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type CreateUserParams struct {
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Role         string  `json:"role"`
	Username     *string `json:"username"`
}

// username é opcional (NULL): se ausente, o User completa via Primeiro
// Acesso no primeiro login (ver SetUsername).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, active, created_at, updated_at, username FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, name, email, password_hash, role, active, created_at, updated_at, username FROM users WHERE email = $1 OR username = $1
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, active, created_at, updated_at, username FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const isUsernameTaken = `-- name: IsUsernameTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1) AS taken
`

func (q *Queries) IsUsernameTaken(ctx context.Context, username *string) (bool, error) {
	row := q.db.QueryRow(ctx, isUsernameTaken, username)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, role, active, created_at, updated_at, username FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setName = `-- name: SetName :one
UPDATE users SET name = $2, updated_at = now() WHERE id = $1 RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type SetNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) SetName(ctx context.Context, arg SetNameParams) (User, error) {
	row := q.db.QueryRow(ctx, setName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const setPasswordHash = `-- name: SetPasswordHash :one
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1 RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type SetPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET active = $2, updated_at = now() WHERE id = $1 RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type SetUserActiveParams struct {
	ID     pgtype.UUID `json:"id"`
	Active bool        `json:"active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.Active)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2, updated_at = now() WHERE id = $1 RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type SetUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const setUsername = `-- name: SetUsername :one
UPDATE users SET username = $2, updated_at = now()
WHERE id = $1 AND username IS NULL
RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type SetUsernameParams struct {
	ID       pgtype.UUID `json:"id"`
	Username *string     `json:"username"`
}

// Só aplica se o User ainda não tiver username — usada pelo Primeiro Acesso.
func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users SET username = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, email, password_hash, role, active, created_at, updated_at, username
`

type UpdateUsernameParams struct {
	ID       pgtype.UUID `json:"id"`
	Username *string     `json:"username"`
}

// Troca o username já definido — usada pela tela de Perfil. Sem a restrição
// username IS NULL do Primeiro Acesso; a unicidade continua garantida pela
// constraint users_username_key.
func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}
