// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_keywords.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWatchKeyword = `-- name: AddWatchKeyword :one
INSERT INTO watch_keywords (watch_id, term) VALUES ($1, $2) RETURNING id, watch_id, term
`

type AddWatchKeywordParams struct {
	WatchID pgtype.UUID `json:"watch_id"`
	Term    string      `json:"term"`
}

func (q *Queries) AddWatchKeyword(ctx context.Context, arg AddWatchKeywordParams) (WatchKeyword, error) {
	row := q.db.QueryRow(ctx, addWatchKeyword, arg.WatchID, arg.Term)
	var i WatchKeyword
	err := row.Scan(&i.ID, &i.WatchID, &i.Term)
	return i, err
}

const deleteAllWatchKeywords = `-- name: DeleteAllWatchKeywords :exec
DELETE FROM watch_keywords WHERE watch_id = $1
`

func (q *Queries) DeleteAllWatchKeywords(ctx context.Context, watchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllWatchKeywords, watchID)
	return err
}

const deleteWatchKeyword = `-- name: DeleteWatchKeyword :exec
DELETE FROM watch_keywords WHERE id = $1 AND watch_id = $2
`

type DeleteWatchKeywordParams struct {
	ID      pgtype.UUID `json:"id"`
	WatchID pgtype.UUID `json:"watch_id"`
}

func (q *Queries) DeleteWatchKeyword(ctx context.Context, arg DeleteWatchKeywordParams) error {
	_, err := q.db.Exec(ctx, deleteWatchKeyword, arg.ID, arg.WatchID)
	return err
}

const listWatchKeywords = `-- name: ListWatchKeywords :many
SELECT id, watch_id, term FROM watch_keywords WHERE watch_id = $1 ORDER BY term
`

func (q *Queries) ListWatchKeywords(ctx context.Context, watchID pgtype.UUID) ([]WatchKeyword, error) {
	rows, err := q.db.Query(ctx, listWatchKeywords, watchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchKeyword
	for rows.Next() {
		var i WatchKeyword
		if err := rows.Scan(&i.ID, &i.WatchID, &i.Term); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
