// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_blocked_words.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWatchBlockedWord = `-- name: AddWatchBlockedWord :one
INSERT INTO watch_blocked_words (watch_id, term) VALUES ($1, $2) RETURNING id, watch_id, term
`

type AddWatchBlockedWordParams struct {
	WatchID pgtype.UUID `json:"watch_id"`
	Term    string      `json:"term"`
}

func (q *Queries) AddWatchBlockedWord(ctx context.Context, arg AddWatchBlockedWordParams) (WatchBlockedWord, error) {
	row := q.db.QueryRow(ctx, addWatchBlockedWord, arg.WatchID, arg.Term)
	var i WatchBlockedWord
	err := row.Scan(&i.ID, &i.WatchID, &i.Term)
	return i, err
}

const deleteAllWatchBlockedWords = `-- name: DeleteAllWatchBlockedWords :exec
DELETE FROM watch_blocked_words WHERE watch_id = $1
`

func (q *Queries) DeleteAllWatchBlockedWords(ctx context.Context, watchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllWatchBlockedWords, watchID)
	return err
}

const deleteWatchBlockedWord = `-- name: DeleteWatchBlockedWord :exec
DELETE FROM watch_blocked_words WHERE id = $1 AND watch_id = $2
`

type DeleteWatchBlockedWordParams struct {
	ID      pgtype.UUID `json:"id"`
	WatchID pgtype.UUID `json:"watch_id"`
}

func (q *Queries) DeleteWatchBlockedWord(ctx context.Context, arg DeleteWatchBlockedWordParams) error {
	_, err := q.db.Exec(ctx, deleteWatchBlockedWord, arg.ID, arg.WatchID)
	return err
}

const listWatchBlockedWords = `-- name: ListWatchBlockedWords :many
SELECT id, watch_id, term FROM watch_blocked_words WHERE watch_id = $1 ORDER BY term
`

func (q *Queries) ListWatchBlockedWords(ctx context.Context, watchID pgtype.UUID) ([]WatchBlockedWord, error) {
	rows, err := q.db.Query(ctx, listWatchBlockedWords, watchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchBlockedWord
	for rows.Next() {
		var i WatchBlockedWord
		if err := rows.Scan(&i.ID, &i.WatchID, &i.Term); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
