// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_marketplaces.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWatchMarketplace = `-- name: AddWatchMarketplace :exec
INSERT INTO watch_marketplaces (watch_id, marketplace_slug)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddWatchMarketplaceParams struct {
	WatchID         pgtype.UUID `json:"watch_id"`
	MarketplaceSlug string      `json:"marketplace_slug"`
}

func (q *Queries) AddWatchMarketplace(ctx context.Context, arg AddWatchMarketplaceParams) error {
	_, err := q.db.Exec(ctx, addWatchMarketplace, arg.WatchID, arg.MarketplaceSlug)
	return err
}

const deleteAllWatchMarketplaces = `-- name: DeleteAllWatchMarketplaces :exec
DELETE FROM watch_marketplaces WHERE watch_id = $1
`

func (q *Queries) DeleteAllWatchMarketplaces(ctx context.Context, watchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllWatchMarketplaces, watchID)
	return err
}

const deleteWatchMarketplacesNotIn = `-- name: DeleteWatchMarketplacesNotIn :exec
DELETE FROM watch_marketplaces
WHERE watch_id = $1 AND marketplace_slug != ALL($2::text[])
`

type DeleteWatchMarketplacesNotInParams struct {
	WatchID          pgtype.UUID `json:"watch_id"`
	MarketplaceSlugs []string    `json:"marketplace_slugs"`
}

func (q *Queries) DeleteWatchMarketplacesNotIn(ctx context.Context, arg DeleteWatchMarketplacesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteWatchMarketplacesNotIn, arg.WatchID, arg.MarketplaceSlugs)
	return err
}

const listWatchMarketplaces = `-- name: ListWatchMarketplaces :many
SELECT marketplace_slug FROM watch_marketplaces WHERE watch_id = $1 ORDER BY marketplace_slug
`

func (q *Queries) ListWatchMarketplaces(ctx context.Context, watchID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listWatchMarketplaces, watchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var marketplace_slug string
		if err := rows.Scan(&marketplace_slug); err != nil {
			return nil, err
		}
		items = append(items, marketplace_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
