// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watches.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWatch = `-- name: CreateWatch :one
INSERT INTO watches (
    user_id, name, target_price_cents, tolerance_percent,
    max_offers, price_drop_threshold_percent, city, state, keyword_match_mode
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at, city, state, keyword_match_mode
`

type CreateWatchParams struct {
	UserID                    pgtype.UUID      `json:"user_id"`
	Name                      string           `json:"name"`
	TargetPriceCents          int64            `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric   `json:"tolerance_percent"`
	MaxOffers                 int32            `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric   `json:"price_drop_threshold_percent"`
	City                      *string          `json:"city"`
	State                     *string          `json:"state"`
	KeywordMatchMode          KeywordMatchMode `json:"keyword_match_mode"`
}

// city/state são opcionais (NULL): quando ausentes, o Scan usa o padrão
// global em scan_settings (default_city/default_state) — ver OLXFetcher.
func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, createWatch,
		arg.UserID,
		arg.Name,
		arg.TargetPriceCents,
		arg.TolerancePercent,
		arg.MaxOffers,
		arg.PriceDropThresholdPercent,
		arg.City,
		arg.State,
		arg.KeywordMatchMode,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.State,
		&i.KeywordMatchMode,
	)
	return i, err
}

const deleteWatch = `-- name: DeleteWatch :exec
DELETE FROM watches WHERE id = $1
`

func (q *Queries) DeleteWatch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWatch, id)
	return err
}

const dueWatchMarketplaces = `-- name: DueWatchMarketplaces :many
SELECT w.id, w.user_id, w.name, w.target_price_cents, w.tolerance_percent, w.max_offers, w.price_drop_threshold_percent, w.active, w.next_scan_at, w.created_at, w.updated_at, w.city, w.state, w.keyword_match_mode, wm.marketplace_slug
FROM watch_marketplaces wm
JOIN watches w ON w.id = wm.watch_id
JOIN users u ON u.id = w.user_id
WHERE w.active
  AND u.active
  AND wm.next_scan_at <= now()
`

type DueWatchMarketplacesRow struct {
	ID                        pgtype.UUID        `json:"id"`
	UserID                    pgtype.UUID        `json:"user_id"`
	Name                      string             `json:"name"`
	TargetPriceCents          int64              `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric     `json:"tolerance_percent"`
	MaxOffers                 int32              `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric     `json:"price_drop_threshold_percent"`
	Active                    bool               `json:"active"`
	NextScanAt                pgtype.Timestamptz `json:"next_scan_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	City                      *string            `json:"city"`
	State                     *string            `json:"state"`
	KeywordMatchMode          KeywordMatchMode   `json:"keyword_match_mode"`
	MarketplaceSlug           string             `json:"marketplace_slug"`
}

// Pares (Watch, marketplace) prontos para rodar um novo Scan: Watch ativo,
// dono ativo, e o next_scan_at daquele marketplace específico já passou —
// cada marketplace de um Watch é agendado e reagendado independentemente
// (ver watch_marketplaces.next_scan_at), não mais o Watch inteiro de uma
// vez. A pausa por dono desativado nunca é persistida como estado do
// Watch — é sempre derivada via join com users.active.
func (q *Queries) DueWatchMarketplaces(ctx context.Context) ([]DueWatchMarketplacesRow, error) {
	rows, err := q.db.Query(ctx, dueWatchMarketplaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueWatchMarketplacesRow
	for rows.Next() {
		var i DueWatchMarketplacesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetPriceCents,
			&i.TolerancePercent,
			&i.MaxOffers,
			&i.PriceDropThresholdPercent,
			&i.Active,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
			&i.State,
			&i.KeywordMatchMode,
			&i.MarketplaceSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchByID = `-- name: GetWatchByID :one
SELECT id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at, city, state, keyword_match_mode FROM watches WHERE id = $1
`

func (q *Queries) GetWatchByID(ctx context.Context, id pgtype.UUID) (Watch, error) {
	row := q.db.QueryRow(ctx, getWatchByID, id)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.State,
		&i.KeywordMatchMode,
	)
	return i, err
}

const listAllWatchesWithOwner = `-- name: ListAllWatchesWithOwner :many
SELECT w.id, w.user_id, w.name, w.target_price_cents, w.tolerance_percent, w.max_offers, w.price_drop_threshold_percent, w.active, w.next_scan_at, w.created_at, w.updated_at, w.city, w.state, w.keyword_match_mode, u.name AS owner_name, u.email AS owner_email
FROM watches w
JOIN users u ON u.id = w.user_id
ORDER BY w.user_id, w.created_at DESC
`

type ListAllWatchesWithOwnerRow struct {
	ID                        pgtype.UUID        `json:"id"`
	UserID                    pgtype.UUID        `json:"user_id"`
	Name                      string             `json:"name"`
	TargetPriceCents          int64              `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric     `json:"tolerance_percent"`
	MaxOffers                 int32              `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric     `json:"price_drop_threshold_percent"`
	Active                    bool               `json:"active"`
	NextScanAt                pgtype.Timestamptz `json:"next_scan_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	City                      *string            `json:"city"`
	State                     *string            `json:"state"`
	KeywordMatchMode          KeywordMatchMode   `json:"keyword_match_mode"`
	OwnerName                 string             `json:"owner_name"`
	OwnerEmail                string             `json:"owner_email"`
}

// Listagem cross-user (admin, ver ?all=true em WatchHandler.List) já com
// nome/email do dono — usada pela tela admin "Todos os Alertas" para exibir
// de quem é cada Alerta sem uma segunda chamada por User.
func (q *Queries) ListAllWatchesWithOwner(ctx context.Context) ([]ListAllWatchesWithOwnerRow, error) {
	rows, err := q.db.Query(ctx, listAllWatchesWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllWatchesWithOwnerRow
	for rows.Next() {
		var i ListAllWatchesWithOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetPriceCents,
			&i.TolerancePercent,
			&i.MaxOffers,
			&i.PriceDropThresholdPercent,
			&i.Active,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
			&i.State,
			&i.KeywordMatchMode,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchesByUser = `-- name: ListWatchesByUser :many
SELECT id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at, city, state, keyword_match_mode FROM watches WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWatchesByUser(ctx context.Context, userID pgtype.UUID) ([]Watch, error) {
	rows, err := q.db.Query(ctx, listWatchesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watch
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetPriceCents,
			&i.TolerancePercent,
			&i.MaxOffers,
			&i.PriceDropThresholdPercent,
			&i.Active,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.City,
			&i.State,
			&i.KeywordMatchMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleWatchMarketplace = `-- name: RescheduleWatchMarketplace :exec
UPDATE watch_marketplaces SET next_scan_at = $3
WHERE watch_id = $1 AND marketplace_slug = $2
`

type RescheduleWatchMarketplaceParams struct {
	WatchID         pgtype.UUID        `json:"watch_id"`
	MarketplaceSlug string             `json:"marketplace_slug"`
	NextScanAt      pgtype.Timestamptz `json:"next_scan_at"`
}

func (q *Queries) RescheduleWatchMarketplace(ctx context.Context, arg RescheduleWatchMarketplaceParams) error {
	_, err := q.db.Exec(ctx, rescheduleWatchMarketplace, arg.WatchID, arg.MarketplaceSlug, arg.NextScanAt)
	return err
}

const setWatchActive = `-- name: SetWatchActive :one
UPDATE watches SET active = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at, city, state, keyword_match_mode
`

type SetWatchActiveParams struct {
	ID     pgtype.UUID `json:"id"`
	Active bool        `json:"active"`
}

func (q *Queries) SetWatchActive(ctx context.Context, arg SetWatchActiveParams) (Watch, error) {
	row := q.db.QueryRow(ctx, setWatchActive, arg.ID, arg.Active)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.State,
		&i.KeywordMatchMode,
	)
	return i, err
}

const updateWatch = `-- name: UpdateWatch :one
UPDATE watches SET
    name = $2,
    target_price_cents = $3,
    tolerance_percent = $4,
    max_offers = $5,
    price_drop_threshold_percent = $6,
    city = $7,
    state = $8,
    keyword_match_mode = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at, city, state, keyword_match_mode
`

type UpdateWatchParams struct {
	ID                        pgtype.UUID      `json:"id"`
	Name                      string           `json:"name"`
	TargetPriceCents          int64            `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric   `json:"tolerance_percent"`
	MaxOffers                 int32            `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric   `json:"price_drop_threshold_percent"`
	City                      *string          `json:"city"`
	State                     *string          `json:"state"`
	KeywordMatchMode          KeywordMatchMode `json:"keyword_match_mode"`
}

func (q *Queries) UpdateWatch(ctx context.Context, arg UpdateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, updateWatch,
		arg.ID,
		arg.Name,
		arg.TargetPriceCents,
		arg.TolerancePercent,
		arg.MaxOffers,
		arg.PriceDropThresholdPercent,
		arg.City,
		arg.State,
		arg.KeywordMatchMode,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.City,
		&i.State,
		&i.KeywordMatchMode,
	)
	return i, err
}
