// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watches.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWatch = `-- name: CreateWatch :one
INSERT INTO watches (
    user_id, name, target_price_cents, tolerance_percent,
    max_offers, price_drop_threshold_percent
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at
`

type CreateWatchParams struct {
	UserID                    pgtype.UUID    `json:"user_id"`
	Name                      string         `json:"name"`
	TargetPriceCents          int64          `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric `json:"tolerance_percent"`
	MaxOffers                 int32          `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric `json:"price_drop_threshold_percent"`
}

func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, createWatch,
		arg.UserID,
		arg.Name,
		arg.TargetPriceCents,
		arg.TolerancePercent,
		arg.MaxOffers,
		arg.PriceDropThresholdPercent,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWatch = `-- name: DeleteWatch :exec
DELETE FROM watches WHERE id = $1
`

func (q *Queries) DeleteWatch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWatch, id)
	return err
}

const dueWatches = `-- name: DueWatches :many
SELECT w.id, w.user_id, w.name, w.target_price_cents, w.tolerance_percent, w.max_offers, w.price_drop_threshold_percent, w.active, w.next_scan_at, w.created_at, w.updated_at
FROM watches w
JOIN users u ON u.id = w.user_id
WHERE w.active
  AND u.active
  AND w.next_scan_at <= now()
`

// Watches prontos para rodar um novo Scan: ativos, dono ativo, e
// next_scan_at já passou. A pausa por dono desativado nunca é persistida
// como estado do Watch — é sempre derivada via join com users.active.
func (q *Queries) DueWatches(ctx context.Context) ([]Watch, error) {
	rows, err := q.db.Query(ctx, dueWatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watch
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetPriceCents,
			&i.TolerancePercent,
			&i.MaxOffers,
			&i.PriceDropThresholdPercent,
			&i.Active,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchByID = `-- name: GetWatchByID :one
SELECT id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at FROM watches WHERE id = $1
`

func (q *Queries) GetWatchByID(ctx context.Context, id pgtype.UUID) (Watch, error) {
	row := q.db.QueryRow(ctx, getWatchByID, id)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWatchesGroupedByUser = `-- name: ListAllWatchesGroupedByUser :many
SELECT id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at FROM watches ORDER BY user_id, created_at DESC
`

func (q *Queries) ListAllWatchesGroupedByUser(ctx context.Context) ([]Watch, error) {
	rows, err := q.db.Query(ctx, listAllWatchesGroupedByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watch
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetPriceCents,
			&i.TolerancePercent,
			&i.MaxOffers,
			&i.PriceDropThresholdPercent,
			&i.Active,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchesByUser = `-- name: ListWatchesByUser :many
SELECT id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at FROM watches WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWatchesByUser(ctx context.Context, userID pgtype.UUID) ([]Watch, error) {
	rows, err := q.db.Query(ctx, listWatchesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watch
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetPriceCents,
			&i.TolerancePercent,
			&i.MaxOffers,
			&i.PriceDropThresholdPercent,
			&i.Active,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleWatch = `-- name: RescheduleWatch :exec
UPDATE watches SET next_scan_at = $2 WHERE id = $1
`

type RescheduleWatchParams struct {
	ID         pgtype.UUID        `json:"id"`
	NextScanAt pgtype.Timestamptz `json:"next_scan_at"`
}

func (q *Queries) RescheduleWatch(ctx context.Context, arg RescheduleWatchParams) error {
	_, err := q.db.Exec(ctx, rescheduleWatch, arg.ID, arg.NextScanAt)
	return err
}

const setWatchActive = `-- name: SetWatchActive :one
UPDATE watches SET active = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at
`

type SetWatchActiveParams struct {
	ID     pgtype.UUID `json:"id"`
	Active bool        `json:"active"`
}

func (q *Queries) SetWatchActive(ctx context.Context, arg SetWatchActiveParams) (Watch, error) {
	row := q.db.QueryRow(ctx, setWatchActive, arg.ID, arg.Active)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWatch = `-- name: UpdateWatch :one
UPDATE watches SET
    name = $2,
    target_price_cents = $3,
    tolerance_percent = $4,
    max_offers = $5,
    price_drop_threshold_percent = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, target_price_cents, tolerance_percent, max_offers, price_drop_threshold_percent, active, next_scan_at, created_at, updated_at
`

type UpdateWatchParams struct {
	ID                        pgtype.UUID    `json:"id"`
	Name                      string         `json:"name"`
	TargetPriceCents          int64          `json:"target_price_cents"`
	TolerancePercent          pgtype.Numeric `json:"tolerance_percent"`
	MaxOffers                 int32          `json:"max_offers"`
	PriceDropThresholdPercent pgtype.Numeric `json:"price_drop_threshold_percent"`
}

func (q *Queries) UpdateWatch(ctx context.Context, arg UpdateWatchParams) (Watch, error) {
	row := q.db.QueryRow(ctx, updateWatch,
		arg.ID,
		arg.Name,
		arg.TargetPriceCents,
		arg.TolerancePercent,
		arg.MaxOffers,
		arg.PriceDropThresholdPercent,
	)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetPriceCents,
		&i.TolerancePercent,
		&i.MaxOffers,
		&i.PriceDropThresholdPercent,
		&i.Active,
		&i.NextScanAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
